"""Cost tracking model for revenue analytics."""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Numeric, Date, DateTime, Text, Boolean, ForeignKey
from app.db.base import Base


class CostEntry(Base):
    """Track costs per category for ROI analytics."""
    __tablename__ = "cost_entries"

    cost_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    tenant_id = Column(Integer, ForeignKey("tenants.tenant_id"), nullable=False, index=True)
    category = Column(String(50), nullable=False, index=True)  # lead_sourcing, contact_discovery, validation, sending, ai
    # 6dp precision so sub-cent per-call AI/token costs are not truncated to $0.00.
    amount = Column(Numeric(12, 6), nullable=False)
    entry_date = Column(Date, nullable=False, index=True)
    notes = Column(Text, nullable=True)
    user_id = Column(Integer, nullable=True)  # Who entered this cost
    is_archived = Column(Boolean, default=False, nullable=False)
    source_adapter = Column(String(50), nullable=True, index=True)  # jsearch, searchapi, usajobs...
    is_automated = Column(Boolean, default=False, nullable=False)  # True = auto-generated by pipeline
    api_calls_count = Column(Integer, nullable=True)
    results_count = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<CostEntry {self.category} ${self.amount} on {self.entry_date}>"
